/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    sermons: Sermon;
    testimonials: Testimonial;
    'prayer-requests': PrayerRequest;
    'zoom-registrations': ZoomRegistration;
    products: Product;
    orders: Order;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'prayer-requests': PrayerRequestsSelect<false> | PrayerRequestsSelect<true>;
    'zoom-registrations': ZoomRegistrationsSelect<false> | ZoomRegistrationsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
    'about-page': AboutPage;
    'ministries-page': MinistriesPage;
    'prayer-mountain-page': PrayerMountainPage;
    'prayer-house-page': PrayerHousePage;
    'bible-college-page': BibleCollegePage;
    'sophia-institute-page': SophiaInstitutePage;
    'sunday-school-page': SundaySchoolPage;
    'church-branches-page': ChurchBranchesPage;
    'events-page': EventsPage;
    'gallery-page': GalleryPage;
    'testimonials-page': TestimonialsPage;
    'give-page': GivePage;
    'contact-page': ContactPage;
    'prayer-request-page': PrayerRequestPage;
    'zoom-lay-hand-page': ZoomLayHandPage;
    'store-page': StorePage;
    'privacy-policy-page': PrivacyPolicyPage;
    'terms-page': TermsPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'ministries-page': MinistriesPageSelect<false> | MinistriesPageSelect<true>;
    'prayer-mountain-page': PrayerMountainPageSelect<false> | PrayerMountainPageSelect<true>;
    'prayer-house-page': PrayerHousePageSelect<false> | PrayerHousePageSelect<true>;
    'bible-college-page': BibleCollegePageSelect<false> | BibleCollegePageSelect<true>;
    'sophia-institute-page': SophiaInstitutePageSelect<false> | SophiaInstitutePageSelect<true>;
    'sunday-school-page': SundaySchoolPageSelect<false> | SundaySchoolPageSelect<true>;
    'church-branches-page': ChurchBranchesPageSelect<false> | ChurchBranchesPageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'testimonials-page': TestimonialsPageSelect<false> | TestimonialsPageSelect<true>;
    'give-page': GivePageSelect<false> | GivePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'prayer-request-page': PrayerRequestPageSelect<false> | PrayerRequestPageSelect<true>;
    'zoom-lay-hand-page': ZoomLayHandPageSelect<false> | ZoomLayHandPageSelect<true>;
    'store-page': StorePageSelect<false> | StorePageSelect<true>;
    'privacy-policy-page': PrivacyPolicyPageSelect<false> | PrivacyPolicyPageSelect<true>;
    'terms-page': TermsPageSelect<false> | TermsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  /**
   * Leave empty to automatically fetch the official video title from YouTube, or enter a custom title.
   */
  title?: string | null;
  /**
   * Paste YouTube video link (watch/share URL), embed URL, or complete <iframe> embed code.
   */
  youtubeUrl: string;
  thumbnail?: (number | null) | Media;
  /**
   * Optional direct image URL or fallback path (e.g., /figma-assets/...)
   */
  customThumbnailUrl?: string | null;
  speaker?: string | null;
  publishedDate?: string | null;
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  person: string;
  title: string;
  /**
   * Unique URL identifier for the testimony detail page (/testimonials/[slug])
   */
  slug: string;
  category: string;
  image?: (number | null) | Media;
  /**
   * Optional path like /figma-assets/... if no media upload is provided.
   */
  imageFallback?: string | null;
  hindiHeadline: string;
  englishHeadline: string;
  shortDescription: string;
  fullStory: string;
  verse?: string | null;
  isFeatured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests".
 */
export interface PrayerRequest {
  id: number;
  fullName?: string | null;
  firstName: string;
  lastName: string;
  gender: 'Male' | 'Female' | 'Other';
  age: number;
  nationality: string;
  profession?: string | null;
  phone: string;
  email: string;
  address: string;
  relativesName?: string | null;
  relativesPhone?: string | null;
  relativesEmail?: string | null;
  hasSickness?: ('Yes' | 'No') | null;
  hospitalized?: string | null;
  problemNature?: string | null;
  problemDuration?: string | null;
  medications?: string | null;
  dailyLivingImpact?: string | null;
  useBrace?: ('Yes' | 'No') | null;
  useWalkingAid?: ('Yes' | 'No') | null;
  useMedicalDevice?: ('Yes' | 'No') | null;
  dailyActivitiesNormal?: ('Yes' | 'No') | null;
  surgeryTherapyDetails?: string | null;
  howDidYouHear?: string | null;
  comments?: string | null;
  status?: ('pending' | 'prayed' | 'contacted' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zoom-registrations".
 */
export interface ZoomRegistration {
  id: number;
  fullName?: string | null;
  firstName: string;
  gender: 'Male' | 'Female' | 'Other';
  age: number;
  nationality: string;
  profession: string;
  email: string;
  phone: string;
  relativeName?: string | null;
  relativePhone?: string | null;
  relativeEmail?: string | null;
  healthSituation: string;
  address: string;
  problemNature: string;
  duration: string;
  dailyLifeEffect: string;
  hospitalized: 'Yes' | 'No';
  medicalDevices: 'Yes' | 'No';
  zoomAvailability: string;
  additionalComments?: string | null;
  status?: ('pending' | 'scheduled' | 'completed' | 'cancelled') | null;
  scheduledZoomLink?: string | null;
  scheduledDateTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Direct link to external e-commerce store (e.g. Amazon, Flipkart, or online shop) that opens in a new tab.
   */
  productUrl?: string | null;
  category: 'Book' | 'Hymnal' | 'Teaching' | 'Merchandise' | 'Other';
  image?: (number | null) | Media;
  imageFallback?: string | null;
  originalPrice: number;
  salePrice: number;
  rating?: number | null;
  description: string;
  inStock?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  productTitle: string;
  quantity: number;
  unitPrice?: number | null;
  totalAmount: number;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  shippingAddress: string;
  city: string;
  pincode: string;
  status?: ('pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'prayer-requests';
        value: number | PrayerRequest;
      } | null)
    | ({
        relationTo: 'zoom-registrations';
        value: number | ZoomRegistration;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  thumbnail?: T;
  customThumbnailUrl?: T;
  speaker?: T;
  publishedDate?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  person?: T;
  title?: T;
  slug?: T;
  category?: T;
  image?: T;
  imageFallback?: T;
  hindiHeadline?: T;
  englishHeadline?: T;
  shortDescription?: T;
  fullStory?: T;
  verse?: T;
  isFeatured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-requests_select".
 */
export interface PrayerRequestsSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  gender?: T;
  age?: T;
  nationality?: T;
  profession?: T;
  phone?: T;
  email?: T;
  address?: T;
  relativesName?: T;
  relativesPhone?: T;
  relativesEmail?: T;
  hasSickness?: T;
  hospitalized?: T;
  problemNature?: T;
  problemDuration?: T;
  medications?: T;
  dailyLivingImpact?: T;
  useBrace?: T;
  useWalkingAid?: T;
  useMedicalDevice?: T;
  dailyActivitiesNormal?: T;
  surgeryTherapyDetails?: T;
  howDidYouHear?: T;
  comments?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zoom-registrations_select".
 */
export interface ZoomRegistrationsSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  gender?: T;
  age?: T;
  nationality?: T;
  profession?: T;
  email?: T;
  phone?: T;
  relativeName?: T;
  relativePhone?: T;
  relativeEmail?: T;
  healthSituation?: T;
  address?: T;
  problemNature?: T;
  duration?: T;
  dailyLifeEffect?: T;
  hospitalized?: T;
  medicalDevices?: T;
  zoomAvailability?: T;
  additionalComments?: T;
  status?: T;
  scheduledZoomLink?: T;
  scheduledDateTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  productUrl?: T;
  category?: T;
  image?: T;
  imageFallback?: T;
  originalPrice?: T;
  salePrice?: T;
  rating?: T;
  description?: T;
  inStock?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  productTitle?: T;
  quantity?: T;
  unitPrice?: T;
  totalAmount?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  shippingAddress?: T;
  city?: T;
  pincode?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  logoFallback?: string | null;
  brandName?: string | null;
  navItems?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButtonLabel?: string | null;
  ctaButtonUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  logoFallback?: string | null;
  ministryName?: string | null;
  aboutText?: string | null;
  copyrightText?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  privacyPolicyUrl?: string | null;
  termsUrl?: string | null;
  pagesList?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        name: string;
        url: string;
        icon?: (number | null) | Media;
        iconFallback?: string | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  mapEmbedUrl?: string | null;
  mapImage?: (number | null) | Media;
  mapImageFallback?: string | null;
  mapUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeadline1?: string | null;
  heroHeadline2?: string | null;
  heroMobileHeadline2?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  mogHeaderTitle?: string | null;
  mogBadgeTitle?: string | null;
  mogSlides?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        title?: string | null;
        subtitle?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  leaderName?: string | null;
  leaderRole?: string | null;
  leaderBio?: string | null;
  knowMoreLink?: string | null;
  knowMoreLabel?: string | null;
  actionCards?:
    | {
        title: string;
        image?: (number | null) | Media;
        imageFallback?: string | null;
        href: string;
        buttonVariant?: ('solid' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  scheduleHeaderTitle?: string | null;
  scheduleVideoBannerUrl?: string | null;
  weeklyServices?:
    | {
        emoji?: string | null;
        title: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  dailyPrograms?:
    | {
        emoji?: string | null;
        title: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  joinLiveLink?: string | null;
  joinLiveLabel?: string | null;
  socialHeaderTitle?: string | null;
  socialSubtitle?: string | null;
  socialPlatforms?:
    | {
        name: string;
        url: string;
        icon?: (number | null) | Media;
        iconFallback?: string | null;
        themeGradient?: string | null;
        borderColor?: string | null;
        id?: string | null;
      }[]
    | null;
  sermonsHeaderTitle?: string | null;
  sermonsFeaturedVideoImage?: (number | null) | Media;
  sermonsFeaturedVideoFallback?: string | null;
  sermonsFeaturedVideoAlt?: string | null;
  sermonsFeaturedVideoUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  vmIdentityBadge?: string | null;
  vmHeaderTitle?: string | null;
  visionTitle?: string | null;
  visionDescription?: string | null;
  missionTitle?: string | null;
  missionDescription?: string | null;
  leadersHeaderTitle?: string | null;
  leaderImages?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        title?: string | null;
        subtitle?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  leaderParagraph1?: string | null;
  leaderParagraph2?: string | null;
  leaderParagraph3?: string | null;
  statsHeaderTitle?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  resourcesHeaderTitle?: string | null;
  resourcesDescription?: string | null;
  resourcesStoreLink?: string | null;
  resourcesStoreLabel?: string | null;
  resourcesBgImage?: (number | null) | Media;
  resourcesBgFallback?: string | null;
  resourcesFgImage?: (number | null) | Media;
  resourcesFgFallback?: string | null;
  crusadesHeaderTitle?: string | null;
  crusadeImages?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        title?: string | null;
        location?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  presenceHeaderTitle?: string | null;
  presenceSubtitle?: string | null;
  presenceRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        title?: string | null;
        country?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  presenceRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        title?: string | null;
        country?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries-page".
 */
export interface MinistriesPage {
  id: number;
  heroBadgeText?: string | null;
  heroSubtitle?: string | null;
  heroVideo?: (number | null) | Media;
  heroVideoFallback?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  overviewHeaderTitle?: string | null;
  ministryCards?:
    | {
        title: string;
        subtitle: string;
        image?: (number | null) | Media;
        imageFallback?: string | null;
        linkUrl: string;
        buttonLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  headChurchHeaderTitle?: string | null;
  headChurchImage?: (number | null) | Media;
  headChurchFallback?: string | null;
  headChurchAlt?: string | null;
  headChurchNarrative?: string | null;
  worshipHeaderTitle?: string | null;
  worshipImage?: (number | null) | Media;
  worshipFallback?: string | null;
  worshipAlt?: string | null;
  worshipNarrative?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-mountain-page".
 */
export interface PrayerMountainPage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  heroSubtitle?: string | null;
  scenesHeaderTitle?: string | null;
  scenesRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  scenesRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  whatIsCardTitle?: string | null;
  whatIsCardDescription?: string | null;
  visionCardTitle?: string | null;
  purposeParagraph?: string | null;
  visionParagraph?: string | null;
  testimoniesHeaderTitle?: string | null;
  testimonies?:
    | {
        person: string;
        title: string;
        summary: string;
        slug?: string | null;
        buttonLabel?: string | null;
        image?: (number | null) | Media;
        imageFallback?: string | null;
        id?: string | null;
      }[]
    | null;
  joinHeaderTitle?: string | null;
  timeCardTitle?: string | null;
  timeCardDescription?: string | null;
  locationCardTitle?: string | null;
  locationCardDescription?: string | null;
  locationUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-house-page".
 */
export interface PrayerHousePage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  heroSubtitle?: string | null;
  scenesHeaderTitle?: string | null;
  scenesRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  scenesRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  whatIsCardTitle?: string | null;
  whatIsCardDescription?: string | null;
  visionCardTitle?: string | null;
  purposeParagraph?: string | null;
  visionParagraph?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-college-page".
 */
export interface BibleCollegePage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  heroSubtitle?: string | null;
  scenesHeaderTitle?: string | null;
  scenesRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  scenesRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  whatIsCardTitle?: string | null;
  whatIsCardDescription?: string | null;
  visionCardTitle?: string | null;
  purposeParagraph?: string | null;
  visionParagraph?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sophia-institute-page".
 */
export interface SophiaInstitutePage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  heroSubtitle?: string | null;
  scenesHeaderTitle?: string | null;
  scenesRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  scenesRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  whatIsCardTitle?: string | null;
  whatIsCardDescription?: string | null;
  visionCardTitle?: string | null;
  purposeParagraph?: string | null;
  visionParagraph?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sunday-school-page".
 */
export interface SundaySchoolPage {
  id: number;
  heroHeaderTitle?: string | null;
  heroDescription?: string | null;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  heroVideoUrl?: string | null;
  heroSubtitle?: string | null;
  scenesHeaderTitle?: string | null;
  scenesRow1?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  scenesRow2?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  whatIsCardTitle?: string | null;
  whatIsCardDescription?: string | null;
  visionCardTitle?: string | null;
  purposeParagraph?: string | null;
  visionParagraph?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-branches-page".
 */
export interface ChurchBranchesPage {
  id: number;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  heroBannerAlt?: string | null;
  headBranchTitle?: string | null;
  /**
   * Enter a Google Maps embed URL (https://www.google.com/maps/embed?...) or full <iframe> code. If provided, an interactive Google Map will be displayed.
   */
  headBranchMapIframe?: string | null;
  headBranchMapImage?: (number | null) | Media;
  headBranchMapFallback?: string | null;
  headBranchHelperText?: string | null;
  directoryHeaderTitle?: string | null;
  nationalBranches?:
    | {
        name: string;
        line1: string;
        line2: string;
        /**
         * Custom Google Maps link for this branch. If empty, an automatic search link will be generated when clicked.
         */
        mapLink?: string | null;
        id?: string | null;
      }[]
    | null;
  internationalBranches?:
    | {
        name: string;
        line1: string;
        line2: string;
        /**
         * Custom Google Maps link for this branch. If empty, an automatic search link will be generated when clicked.
         */
        mapLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  eventsSectionTitle?: string | null;
  upcomingSectionTitle?: string | null;
  events?:
    | {
        title: string;
        cardPoster?: (number | null) | Media;
        cardPosterFallback?: string | null;
        buttonLabel?: string | null;
        detailPoster?: (number | null) | Media;
        detailPosterFallback?: string | null;
        headingGreeting?: string | null;
        subheading?: string | null;
        announcementParagraph1: string;
        announcementParagraph2?: string | null;
        announcementParagraph3?: string | null;
        announcementParagraph4?: string | null;
        scheduleDay?: string | null;
        scheduleDate?: string | null;
        scheduleTime?: string | null;
        scheduleVenue?: string | null;
        schedulePostedBy?: string | null;
        customLinkText?: string | null;
        customLinkUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  photoArch?: {
    image?: (number | null) | Media;
    imageFallback?: string | null;
    alt?: string | null;
    caption?: string | null;
  };
  topRowSidePhotos?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  middleRowPhotos?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  bottomRowSidePhotosLeft?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  photoPodiumHero?: {
    image?: (number | null) | Media;
    imageFallback?: string | null;
    alt?: string | null;
    caption?: string | null;
  };
  bottomRowSidePhotosRight?:
    | {
        image?: (number | null) | Media;
        imageFallback?: string | null;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page".
 */
export interface TestimonialsPage {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  ctaTitle?: string | null;
  ctaQuote?: string | null;
  ctaButton1Label?: string | null;
  ctaButton1Url?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "give-page".
 */
export interface GivePage {
  id: number;
  heroTitle?: string | null;
  scriptureVerse?: string | null;
  purposeStatement?: string | null;
  qrHeaderTitle?: string | null;
  iciciQrImage?: (number | null) | Media;
  iciciQrFallback?: string | null;
  hdfcQrImage?: (number | null) | Media;
  hdfcQrFallback?: string | null;
  axisLogo?: (number | null) | Media;
  axisLogoFallback?: string | null;
  axisQrImage?: (number | null) | Media;
  axisQrFallback?: string | null;
  gpayQrImage?: (number | null) | Media;
  gpayQrFallback?: string | null;
  bankHeaderTitle?: string | null;
  bankAccounts?:
    | {
        bankName: string;
        logo?: (number | null) | Media;
        logoFallback?: string | null;
        accountHolder?: string | null;
        accountNumber: string;
        ifsc: string;
        branch?: string | null;
        borderColor?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroImageFallback?: string | null;
  heroImageBadgeTitle?: string | null;
  heroImageBadgeSubtitle?: string | null;
  formSuccessTitle?: string | null;
  formSuccessMessage?: string | null;
  infoSectionTitle?: string | null;
  infoSectionSubtitle?: string | null;
  generalInquiriesTitle?: string | null;
  generalInquiriesEmail1?: string | null;
  generalInquiriesEmail2?: string | null;
  hospitalLineTitle?: string | null;
  hospitalLineEmail?: string | null;
  emergencyPrayersTitle?: string | null;
  emergencyPrayersEmail?: string | null;
  phoneSectionTitle?: string | null;
  phoneNumber?: string | null;
  addressSectionTitle?: string | null;
  fullAddress?: string | null;
  googleMapsUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-request-page".
 */
export interface PrayerRequestPage {
  id: number;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  headingTitle?: string | null;
  headingSubtitle?: string | null;
  helplineTitle?: string | null;
  helplinePhone?: string | null;
  helplineEmail?: string | null;
  submitButtonText?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  successVerse?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zoom-lay-hand-page".
 */
export interface ZoomLayHandPage {
  id: number;
  heroBannerImage?: (number | null) | Media;
  heroBannerFallback?: string | null;
  headingTitle?: string | null;
  headingSubtitle?: string | null;
  guidelinesTitle?: string | null;
  guidelinesText?: string | null;
  supportPhone?: string | null;
  supportEmail?: string | null;
  submitButtonText?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-page".
 */
export interface StorePage {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  fastDeliveryText?: string | null;
  securePaymentText?: string | null;
  supportPhone?: string | null;
  supportEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page".
 */
export interface PrivacyPolicyPage {
  id: number;
  pageTitle?: string | null;
  introText?: string | null;
  sections?:
    | {
        sectionTitle: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page".
 */
export interface TermsPage {
  id: number;
  pageTitle?: string | null;
  introText?: string | null;
  sections?:
    | {
        sectionTitle: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoFallback?: T;
  brandName?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButtonLabel?: T;
  ctaButtonUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  logoFallback?: T;
  ministryName?: T;
  aboutText?: T;
  copyrightText?: T;
  contactEmail?: T;
  contactPhone?: T;
  privacyPolicyUrl?: T;
  termsUrl?: T;
  pagesList?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        name?: T;
        url?: T;
        icon?: T;
        iconFallback?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  mapEmbedUrl?: T;
  mapImage?: T;
  mapImageFallback?: T;
  mapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadline1?: T;
  heroHeadline2?: T;
  heroMobileHeadline2?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  mogHeaderTitle?: T;
  mogBadgeTitle?: T;
  mogSlides?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        title?: T;
        subtitle?: T;
        alt?: T;
        id?: T;
      };
  leaderName?: T;
  leaderRole?: T;
  leaderBio?: T;
  knowMoreLink?: T;
  knowMoreLabel?: T;
  actionCards?:
    | T
    | {
        title?: T;
        image?: T;
        imageFallback?: T;
        href?: T;
        buttonVariant?: T;
        id?: T;
      };
  scheduleHeaderTitle?: T;
  scheduleVideoBannerUrl?: T;
  weeklyServices?:
    | T
    | {
        emoji?: T;
        title?: T;
        time?: T;
        id?: T;
      };
  dailyPrograms?:
    | T
    | {
        emoji?: T;
        title?: T;
        time?: T;
        id?: T;
      };
  joinLiveLink?: T;
  joinLiveLabel?: T;
  socialHeaderTitle?: T;
  socialSubtitle?: T;
  socialPlatforms?:
    | T
    | {
        name?: T;
        url?: T;
        icon?: T;
        iconFallback?: T;
        themeGradient?: T;
        borderColor?: T;
        id?: T;
      };
  sermonsHeaderTitle?: T;
  sermonsFeaturedVideoImage?: T;
  sermonsFeaturedVideoFallback?: T;
  sermonsFeaturedVideoAlt?: T;
  sermonsFeaturedVideoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  vmIdentityBadge?: T;
  vmHeaderTitle?: T;
  visionTitle?: T;
  visionDescription?: T;
  missionTitle?: T;
  missionDescription?: T;
  leadersHeaderTitle?: T;
  leaderImages?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        title?: T;
        subtitle?: T;
        alt?: T;
        id?: T;
      };
  leaderParagraph1?: T;
  leaderParagraph2?: T;
  leaderParagraph3?: T;
  statsHeaderTitle?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  resourcesHeaderTitle?: T;
  resourcesDescription?: T;
  resourcesStoreLink?: T;
  resourcesStoreLabel?: T;
  resourcesBgImage?: T;
  resourcesBgFallback?: T;
  resourcesFgImage?: T;
  resourcesFgFallback?: T;
  crusadesHeaderTitle?: T;
  crusadeImages?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        title?: T;
        location?: T;
        alt?: T;
        id?: T;
      };
  presenceHeaderTitle?: T;
  presenceSubtitle?: T;
  presenceRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        title?: T;
        country?: T;
        alt?: T;
        id?: T;
      };
  presenceRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        title?: T;
        country?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministries-page_select".
 */
export interface MinistriesPageSelect<T extends boolean = true> {
  heroBadgeText?: T;
  heroSubtitle?: T;
  heroVideo?: T;
  heroVideoFallback?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  overviewHeaderTitle?: T;
  ministryCards?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        imageFallback?: T;
        linkUrl?: T;
        buttonLabel?: T;
        id?: T;
      };
  headChurchHeaderTitle?: T;
  headChurchImage?: T;
  headChurchFallback?: T;
  headChurchAlt?: T;
  headChurchNarrative?: T;
  worshipHeaderTitle?: T;
  worshipImage?: T;
  worshipFallback?: T;
  worshipAlt?: T;
  worshipNarrative?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-mountain-page_select".
 */
export interface PrayerMountainPageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  heroSubtitle?: T;
  scenesHeaderTitle?: T;
  scenesRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  scenesRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  whatIsCardTitle?: T;
  whatIsCardDescription?: T;
  visionCardTitle?: T;
  purposeParagraph?: T;
  visionParagraph?: T;
  testimoniesHeaderTitle?: T;
  testimonies?:
    | T
    | {
        person?: T;
        title?: T;
        summary?: T;
        slug?: T;
        buttonLabel?: T;
        image?: T;
        imageFallback?: T;
        id?: T;
      };
  joinHeaderTitle?: T;
  timeCardTitle?: T;
  timeCardDescription?: T;
  locationCardTitle?: T;
  locationCardDescription?: T;
  locationUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-house-page_select".
 */
export interface PrayerHousePageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  heroSubtitle?: T;
  scenesHeaderTitle?: T;
  scenesRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  scenesRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  whatIsCardTitle?: T;
  whatIsCardDescription?: T;
  visionCardTitle?: T;
  purposeParagraph?: T;
  visionParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bible-college-page_select".
 */
export interface BibleCollegePageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  heroSubtitle?: T;
  scenesHeaderTitle?: T;
  scenesRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  scenesRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  whatIsCardTitle?: T;
  whatIsCardDescription?: T;
  visionCardTitle?: T;
  purposeParagraph?: T;
  visionParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sophia-institute-page_select".
 */
export interface SophiaInstitutePageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  heroSubtitle?: T;
  scenesHeaderTitle?: T;
  scenesRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  scenesRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  whatIsCardTitle?: T;
  whatIsCardDescription?: T;
  visionCardTitle?: T;
  purposeParagraph?: T;
  visionParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sunday-school-page_select".
 */
export interface SundaySchoolPageSelect<T extends boolean = true> {
  heroHeaderTitle?: T;
  heroDescription?: T;
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  heroVideoUrl?: T;
  heroSubtitle?: T;
  scenesHeaderTitle?: T;
  scenesRow1?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  scenesRow2?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        id?: T;
      };
  whatIsCardTitle?: T;
  whatIsCardDescription?: T;
  visionCardTitle?: T;
  purposeParagraph?: T;
  visionParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-branches-page_select".
 */
export interface ChurchBranchesPageSelect<T extends boolean = true> {
  heroBannerImage?: T;
  heroBannerFallback?: T;
  heroBannerAlt?: T;
  headBranchTitle?: T;
  headBranchMapIframe?: T;
  headBranchMapImage?: T;
  headBranchMapFallback?: T;
  headBranchHelperText?: T;
  directoryHeaderTitle?: T;
  nationalBranches?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        mapLink?: T;
        id?: T;
      };
  internationalBranches?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        mapLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  eventsSectionTitle?: T;
  upcomingSectionTitle?: T;
  events?:
    | T
    | {
        title?: T;
        cardPoster?: T;
        cardPosterFallback?: T;
        buttonLabel?: T;
        detailPoster?: T;
        detailPosterFallback?: T;
        headingGreeting?: T;
        subheading?: T;
        announcementParagraph1?: T;
        announcementParagraph2?: T;
        announcementParagraph3?: T;
        announcementParagraph4?: T;
        scheduleDay?: T;
        scheduleDate?: T;
        scheduleTime?: T;
        scheduleVenue?: T;
        schedulePostedBy?: T;
        customLinkText?: T;
        customLinkUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  photoArch?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
      };
  topRowSidePhotos?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  middleRowPhotos?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  bottomRowSidePhotosLeft?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  photoPodiumHero?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
      };
  bottomRowSidePhotosRight?:
    | T
    | {
        image?: T;
        imageFallback?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-page_select".
 */
export interface TestimonialsPageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  ctaTitle?: T;
  ctaQuote?: T;
  ctaButton1Label?: T;
  ctaButton1Url?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "give-page_select".
 */
export interface GivePageSelect<T extends boolean = true> {
  heroTitle?: T;
  scriptureVerse?: T;
  purposeStatement?: T;
  qrHeaderTitle?: T;
  iciciQrImage?: T;
  iciciQrFallback?: T;
  hdfcQrImage?: T;
  hdfcQrFallback?: T;
  axisLogo?: T;
  axisLogoFallback?: T;
  axisQrImage?: T;
  axisQrFallback?: T;
  gpayQrImage?: T;
  gpayQrFallback?: T;
  bankHeaderTitle?: T;
  bankAccounts?:
    | T
    | {
        bankName?: T;
        logo?: T;
        logoFallback?: T;
        accountHolder?: T;
        accountNumber?: T;
        ifsc?: T;
        branch?: T;
        borderColor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroImageFallback?: T;
  heroImageBadgeTitle?: T;
  heroImageBadgeSubtitle?: T;
  formSuccessTitle?: T;
  formSuccessMessage?: T;
  infoSectionTitle?: T;
  infoSectionSubtitle?: T;
  generalInquiriesTitle?: T;
  generalInquiriesEmail1?: T;
  generalInquiriesEmail2?: T;
  hospitalLineTitle?: T;
  hospitalLineEmail?: T;
  emergencyPrayersTitle?: T;
  emergencyPrayersEmail?: T;
  phoneSectionTitle?: T;
  phoneNumber?: T;
  addressSectionTitle?: T;
  fullAddress?: T;
  googleMapsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prayer-request-page_select".
 */
export interface PrayerRequestPageSelect<T extends boolean = true> {
  heroBannerImage?: T;
  heroBannerFallback?: T;
  headingTitle?: T;
  headingSubtitle?: T;
  helplineTitle?: T;
  helplinePhone?: T;
  helplineEmail?: T;
  submitButtonText?: T;
  successTitle?: T;
  successMessage?: T;
  successVerse?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zoom-lay-hand-page_select".
 */
export interface ZoomLayHandPageSelect<T extends boolean = true> {
  heroBannerImage?: T;
  heroBannerFallback?: T;
  headingTitle?: T;
  headingSubtitle?: T;
  guidelinesTitle?: T;
  guidelinesText?: T;
  supportPhone?: T;
  supportEmail?: T;
  submitButtonText?: T;
  successTitle?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-page_select".
 */
export interface StorePageSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  fastDeliveryText?: T;
  securePaymentText?: T;
  supportPhone?: T;
  supportEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page_select".
 */
export interface PrivacyPolicyPageSelect<T extends boolean = true> {
  pageTitle?: T;
  introText?: T;
  sections?:
    | T
    | {
        sectionTitle?: T;
        content?: T;
        id?: T;
      };
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page_select".
 */
export interface TermsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  introText?: T;
  sections?:
    | T
    | {
        sectionTitle?: T;
        content?: T;
        id?: T;
      };
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}